name: Release Tribot Dax Walker
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-11
        with:
          args: publish -PtribotDeployToken=${{ secrets.MavenDeployKey }} -Pversion=${{ github.event.release.tag_name }}